### ISSUE TITLE
problem running myocyte-rodinia-3.1 (SIGABRT)

### ISSUE THREAD

**Issue by DarkC343** [accel-sim/gpu-app-collection#14]
I am trying to run `./myocyte-rodinia-3.1 100 1 0` using gdb and I get the following error:
_`GPGPU-Sim PTX: ... end of reconvergence points for __internal_accurate_pow`
`GPGPU-Sim PTX: ... done pre-decoding instructions for '__internal_accurate_pow'.`_
`free(): double free detected in tcache 2`

`Thread 2 "myocyte-rodinia" received signal SIGABRT, Aborted.`
`[Switching to Thread 0x7ffff5a92700 (LWP 20856)]`
`__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51`
`51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.`
`(gdb) backtrace`
`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51`
`#1  0x00007ffff6f877f1 in __GI_abort () at abort.c:79`
`#2  0x00007ffff6fd0837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff70fda7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181`
`#3  0x00007ffff6fd78ba in malloc_printerr (str=str@entry=0x7ffff70ff6e8 "free(): double free detected in tcache 2") at malloc.c:5342`
`#4  0x00007ffff6fdf0ed in _int_free (have_lock=0, p=0x7ffff00ae570, av=0x7ffff0000020) at malloc.c:4195`
`#5  __GI___libc_free (mem=0x7ffff00ae580) at malloc.c:3134`
`#6  0x00007ffff78445c1 in arg_buffer_t::~arg_buffer_t (this=<optimized out>, __in_chrg=<optimized out>) at ./ptx_ir.h:1449`
`#7  __gnu_cxx::new_allocator<std::_List_node<arg_buffer_t> >::destroy<arg_buffer_t> (this=<optimized out>, __p=<optimized out>)`
`    at /usr/include/c++/7/ext/new_allocator.h:140`
`#8  std::allocator_traits<std::allocator<std::_List_node<arg_buffer_t> > >::destroy<arg_buffer_t> (__a=..., __p=<optimized out>)`
`    at /usr/include/c++/7/bits/alloc_traits.h:487`
`#9  std::__cxx11::_List_base<arg_buffer_t, std::allocator<arg_buffer_t> >::_M_clear (this=0x7ffff5a918b0) at /usr/include/c++/7/bits/list.tcc:76`
`#10 std::__cxx11::_List_base<arg_buffer_t, std::allocator<arg_buffer_t> >::~_List_base (this=0x7ffff5a918b0, __in_chrg=<optimized out>)`
`    at /usr/include/c++/7/bits/stl_list.h:442`
`#11 std::__cxx11::list<arg_buffer_t, std::allocator<arg_buffer_t> >::~list (this=0x7ffff5a918b0, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_list.h:733`
`#12 call_impl (pI=pI@entry=0x5555678528a0, thread=thread@entry=0x7ffff0016b00) at instructions.cc:2210`
`#13 0x00007ffff7831f0c in ptx_thread_info::ptx_exec_inst (this=0x7ffff0016b00, inst=..., lane_id=lane_id@entry=0) at opcodes.def:58`
`#14 0x00007ffff79d3318 in core_t::execute_warp_inst_t (this=this@entry=0x55555765e780, inst=..., warpId=0, warpId@entry=4294967295) at abstract_hardware_model.cc:1192`
`#15 0x00007ffff7911402 in exec_shader_core_ctx::func_exec_inst (inst=..., this=0x55555765e780) at shader.cc:1028`
`#16 shader_core_ctx::issue_warp (this=0x55555765e780, pipe_reg_set=..., next_inst=0x5555678528a0, active_mask=..., warp_id=0, sch_id=0) at shader.cc:1051`
`#17 0x00007ffff79045af in scheduler_unit::cycle (this=0x5555576fc9c0) at shader.cc:1363`
`#18 0x00007ffff790481e in shader_core_ctx::issue (this=this@entry=0x55555765e780) at shader.cc:1073`
`#19 0x00007ffff7913a53 in shader_core_ctx::cycle (this=0x55555765e780) at shader.cc:3574`
`#20 0x00007ffff7913ad8 in simt_core_cluster::core_cycle (this=0x55555765e6e0) at shader.cc:4382`
`#21 0x00007ffff78da1c3 in gpgpu_sim::cycle (this=0x555555844290) at gpu-sim.cc:1977`
`#22 0x00007ffff79dd71d in gpgpu_sim_thread_concurrent (ctx_ptr=0x55555582bd30) at gpgpusim_entrypoint.cc:592`
`#23 0x00007ffff62b46db in start_thread (arg=0x7ffff5a92700) at pthread_create.c:463`
`#24 0x00007ffff706861f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`
How can I resolve this issue?

**Comment by tgrogers** [comment]
Thanks for the issue; it looks like you are running this with Accel-Sim - please specify the simulator setup so that we can reproduce it if it still happens, if not let's close the issue.
